Fix for PHP8 and MySQL8. Refactoring in the search engine to be able to choose the database engine to use.
Meneame/meneame.net pull request #66
Opened 2024-11-16 17:52 UTC by migrad

- Many bugs that prevented it from working correctly in PHP 8 have been fixed.
- Fixed many queries that contained keywords that were deprecated or not compatible with MySQL 8
- The search engine has been modified so that the database engine can be easily changed through the settings.
- MySQL has been configured as the default database engine for the search engine.
- Changes have been made to the database schema to add new indexes to the links and comments tables.

I don't have a large enough dataset to properly test the changes. Test it first in a test environment before taking it to production.

2025-03-05 22:40 UTC, robertolopezlopez requested changes
I doubt that you are fixing anything with this PR

2025-03-05 22:40 UTC, robertolopezlopez commented on composer.json
> +    "crodas/haanga": "1.0.*",
Why? This is very suspicious

2025-03-05 22:40 UTC, robertolopezlopez commented on install/install.sh
> +    VALUES (1,'Shadows236','god',0,'2018-10-10 21:41:28','2018-10-10 12:04:33','2018-10-10 21:42:28','127.0.0.1','sha256:JKVNPRNe5ZM2OvQ7Re42rUxYitMiMUMe:5d62fa6c578d2166b8b89732f0e8656ed54199df4fbaf
Why? Who is "Shadows236" and why does he need a superuser? Why are you inserting this data here on the first place?

2025-03-05 22:40 UTC, robertolopezlopez commented on install/install.sh
> +    https://gist.githubusercontent.com/cristiannsc/aa115a3257ecc90430de15ade1cc0d5f/raw/localhost-local.php
Any reason for this?

2025-03-05 22:40 UTC, robertolopezlopez commented on install/install.sh
> +sed -i 's/;extension=shmop/;extension=shmop\nextension=mcrypt.so\nextension=memcache.so/g' /etc/php/7.2/fpm/php.ini
Smells bad

2025-03-05 22:40 UTC, robertolopezlopez commented on install/install.sh
> +sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=1/g' /etc/php/7.2/fpm/php.ini
This does not have any effect

2025-03-05 22:40 UTC, robertolopezlopez commented on install/install.sh
> +    https://gist.githubusercontent.com/cristiannsc/36c765c85daff7364e2c87639af399da/raw/php_fastcgi
Who is this christiannsc and why all those wget commands to fetch his random gists?

2025-03-05 23:57 UTC, migrad commented
Well, the install.sh script is not mine (it is indicated at the beginning of the script). Yes, it is quite old, but at the time it helped me to facilitate the local installation and configuration of meneame.net. Something interesting since there is no documentation for the project.

"Why? This is very suspicious"

Suspicious? Really? How long has it been since you ran a "composer install" or "composer update"? It gives an error:

require.crodas/Haanga is invalid, it should not contain uppercase characters. Please use crodas/haanga instead.

I created this PR to provide a solution to the search engine problem, but of course, this repository is abandoned and many changes are needed to make it work on PHP8 in the first place.

But no problem.

2025-03-05 23:57 UTC, closed without merging

2025-03-06 09:40 UTC, robertolopezlopez commented
ok, I can understand that it is not yours - but it is very unsafe to just wget everything you find on the internet without knowing what's in there, or if tomorrow it will change without any notice (those things happen every day)

2025-03-06 09:41 UTC, robertolopezlopez commented
regarding haanga - ok, I didn't really check what that was. Thanks for your explanation